version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.17.10
    container_name: kibana
    environment:
      - discovery.type=single-node
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  filebeat:
    image: elastic/filebeat:7.17.10
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/app:ro
    depends_on:
      - elasticsearch

  calendar-bot:
    image: jorres/calendar-bot
    volumes:
      - ./logs:/logs

volumes:
  esdata:
    driver: local
