name: build-and-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: build
      run: go build -v ./...
    - name: test
      run: go test -v ./...
    - name: init-token
      run: |
        echo ${{ secrets.TELEGRAM_BOT_TOKEN }} > token.txt
        echo ${{ secrets.BOT_ID }} > bot_id.txt
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin <<<'${{ secrets.DOCKER_PASSWORD }}'
        docker build -t jorres/calendar-bot:latest .
        docker push jorres/calendar-bot
