name: build-and-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: build
      run: go build -v ./...
    - name: test
      run: go test -v ./...
    - name: test-image-builds
      run: |
        # For testing purposes, we just fake a file with the token. 
        # The image built there is not going to be deployed anyway.
        echo "abc" > token.txt
        docker build -t jorres/calendar-bot .
